"""Rubric mapping helpers.

Rubric threshold tables were not included in the prompt. The CSV generated by
the pipeline is therefore a template with `MISSING` threshold fields. No rubric
scores are inferred from unspecified thresholds.
"""

from __future__ import annotations

import pandas as pd

from src.config import RUBRIC_METRICS
from src.schemas import RUBRIC_MAPPING_COLUMNS


def missing_rubric_template() -> pd.DataFrame:
    """Create a rubric CSV template with unspecified thresholds marked missing."""

    rows = []
    for metric in RUBRIC_METRICS:
        rows.append(
            {
                "metric_name": metric,
                "source_signals": "MISSING",
                "threshold_rule": "MISSING",
                "score_1": "MISSING",
                "score_2": "MISSING",
                "score_3": "MISSING",
                "score_4": "MISSING",
                "score_5": "MISSING",
                "comments": "Rubric mapping was not provided in the recovered data.",
            }
        )
    return pd.DataFrame(rows, columns=RUBRIC_MAPPING_COLUMNS)


def apply_rubric_scores(df: pd.DataFrame, mappings: pd.DataFrame) -> pd.DataFrame:
    """Return df unchanged because no explicit thresholds were provided."""

    return df.copy()
